# Generated by Django 3.1.7 on 2021-04-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OohUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('currentQuestionRun', models.IntegerField(default=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('housenumber', models.CharField(blank=True, max_length=10)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('class_names', models.CharField(blank=True, max_length=100, null=True)),
                ('filter_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeplace', models.BooleanField(default=True)),
                ('promoted', models.BooleanField(default=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('intervalInDays', models.IntegerField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('overcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ooh.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=50)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='locations/%Y/%m')),
                ('pricecat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('bundesland', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firstQuestion', models.BooleanField(default=False)),
                ('lastQuestion', models.BooleanField(default=False)),
                ('priority_in_filtering', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('questionRun', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.question')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.choiceoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('overcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ooh.locationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('mininumage', models.PositiveSmallIntegerField(default=0)),
                ('pricecat', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m')),
                ('eventCategory', models.ManyToManyField(to='ooh.EventCategory')),
                ('eventLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.eventlocation')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('eventTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.eventtemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('eventlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.eventlocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='categories',
            field=models.ManyToManyField(to='ooh.LocationCategory'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ooh.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ooh.eventtemplate'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='nextQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextQuestion', to='ooh.question'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='prevQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevQuestion', to='ooh.question'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ooh.question'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='related_event_category',
            field=models.ManyToManyField(blank=True, to='ooh.EventCategory'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='related_location_category',
            field=models.ManyToManyField(blank=True, to='ooh.LocationCategory'),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='defaultEventLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ooh.eventlocation'),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ooh.location'),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
