# Generated by Django 3.1.7 on 2021-04-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='nextQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextQuestion', to='ooh.question'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='prevQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevQuestion', to='ooh.question'),
        ),
    ]
