# Generated by Django 3.1.7 on 2021-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0002_auto_20210411_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='template',
            new_name='eventTemplate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='interval',
            new_name='intervalInDays',
        ),
        migrations.RenameField(
            model_name='eventlocation',
            old_name='locationID',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='eventlocationrating',
            old_name='eventlocationID',
            new_name='eventlocation',
        ),
        migrations.RenameField(
            model_name='eventrating',
            old_name='eventID',
            new_name='eventTemplate',
        ),
        migrations.RenameField(
            model_name='eventtemplate',
            old_name='category',
            new_name='eventCategory',
        ),
        migrations.RenameField(
            model_name='eventtemplate',
            old_name='location',
            new_name='eventLocation',
        ),
        migrations.RenameField(
            model_name='participate',
            old_name='eventID',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='participate',
            old_name='customerID',
            new_name='user',
        ),
        migrations.AddField(
            model_name='eventrating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
