# Generated by Django 3.1.7 on 2021-03-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0002_oohuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='cityname',
        ),
    ]
