# Generated by Django 3.1.7 on 2021-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0002_choiceoption_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='nextQuestion',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
