# Generated by Django 3.1.7 on 2021-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0003_auto_20210411_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='firstQuestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='lastQuestion',
            field=models.BooleanField(default=False),
        ),
    ]
