# Generated by Django 3.1.7 on 2021-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0003_choiceoption_nextquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='prevQuestion',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
