# Generated by Django 3.1.7 on 2021-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0003_auto_20210304_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oohuser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
