# Generated by Django 3.1.7 on 2021-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0004_choiceoption_prevquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='nextQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextQuestion', to='ooh.question'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='prevQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevQuestion', to='ooh.question'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ooh.question'),
        ),
    ]
