# Generated by Django 3.1.7 on 2021-04-15 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0004_auto_20210412_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='oohuser',
            name='currentQuestionRun',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='class_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('questionRun', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.question')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.choiceoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
