# Generated by Django 3.1.7 on 2021-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0005_auto_20210415_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='filter_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='filter_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='filter_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
