# Generated by Django 3.1.7 on 2021-03-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0005_auto_20210304_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ooh.location'),
            preserve_default=False,
        ),
    ]
