# Generated by Django 3.1.7 on 2021-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0006_auto_20210416_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='related_event_category',
            field=models.ManyToManyField(blank=True, null=True, to='ooh.EventCategory'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='related_location_category',
            field=models.ManyToManyField(blank=True, null=True, to='ooh.LocationCategory'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='filter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='filter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locationcategory',
            name='filter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
