# Generated by Django 3.1.7 on 2021-04-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0007_auto_20210416_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority_in_filtering',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='related_event_category',
            field=models.ManyToManyField(blank=True, to='ooh.EventCategory'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='related_location_category',
            field=models.ManyToManyField(blank=True, to='ooh.LocationCategory'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='mininumage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
