# Generated by Django 3.1.7 on 2021-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0007_auto_20210304_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='housenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
