# Generated by Django 3.1.7 on 2021-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0008_eventlocation_housenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='oohuser',
            name='housenumber',
            field=models.CharField(default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='locationID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ooh.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oohuser',
            name='street',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
