# Generated by Django 3.1.7 on 2021-03-09 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0009_auto_20210309_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='eventlocationrating',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='eventrating',
            name='customerID',
        ),
        migrations.AddField(
            model_name='eventlocationrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oohuser',
            name='defaultEventLocation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ooh.eventlocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participate',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
