# Generated by Django 3.1.7 on 2021-03-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0011_auto_20210309_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oohuser',
            name='locationID',
        ),
        migrations.AddField(
            model_name='oohuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ooh.location'),
        ),
    ]
