# Generated by Django 3.1.7 on 2021-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0013_auto_20210309_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
