# Generated by Django 3.1.7 on 2021-03-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0015_auto_20210312_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrating',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.eventtemplate'),
        ),
    ]
